//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeam12_Latest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CarDetail
    {
        public int CarId { get; set; }
        [DisplayName("LP")]
        public decimal ListPrice { get; set; }
        [DisplayName("DP(%)")]
        public Nullable<decimal> DiscountPercentage { get; set; }
        [DisplayName("CP")]
        public decimal CostPrice { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ListingDate { get; set; }
        [DisplayName("SP")]
        public Nullable<decimal> SellPrice { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> SellDate { get; set; }
        [DisplayName("ModelNo")]
        [Required]
        public string ModelNumber { get; set; }
        [DisplayName("CustName")]
        public string CustomerName { get; set; }
        [Required]
        public string EngineType { get; set; }
        [DisplayName("Capacity")]
        public int SittingCapacity { get; set; }
        [DisplayName("Perf(HP)")]
        public int Performance { get; set; }
        public bool ABS { get; set; }
        [DisplayName("Company")]
        public int CompanyId { get; set; }
        [DisplayName("Usage")]
        public int UsageId { get; set; }

        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual CarType CarType { get; set; }



        public CarDetail()
        {
            ListingDate = DateTime.Now;

        }
        public int TimeInInventory()
        {
            TimeSpan? dateDiff = null;
            if (SellPrice == null)
            {
                dateDiff = DateTime.Now - ListingDate;
                return dateDiff.Value.Days;
            }
            else
            {
                dateDiff = SellDate - ListingDate;
                return dateDiff.Value.Days;
            }
        }

        public decimal CurrentPrice()
        {
            int time = TimeInInventory();
            if (time > 60)
            {
                DiscountPercentage = 25;
            }
            if (DiscountPercentage == null)
            {
                return ListPrice;
            }
            else
            {
                return ListPrice - ((decimal)DiscountPercentage / 100) * ListPrice;
            }
        }

        public decimal? Profit()
        {
            if (SellPrice == null)
            {
                return null;
            }
            else
            {
                return SellPrice - CostPrice;
            }

        }

        public Boolean IsSold()
        {
            if (SellPrice == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

       
    }
}
