//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeam12_Latest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarType
    {
        public CarType()
        {
            this.CarDetails = new HashSet<CarDetail>();
        }
    
        public string UsageType { get; set; }
        public int UsageId { get; set; }
    
        public virtual ICollection<CarDetail> CarDetails { get; set; }
    }
}
