//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeam12_Latest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CompanyDetail
    {
        public CompanyDetail()
        {
            this.CarDetails = new HashSet<CarDetail>();
        }
    
        public int CompanyId { get; set; }
        [DisplayName("Company")] 
        public string CompanyName { get; set; }
        public string HeadQuartersAt { get; set; }
        public int NoOFEmployees { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime SetUpYear { get; set; }
    
        public virtual ICollection<CarDetail> CarDetails { get; set; }
    }
}
